### ISSUE TITLE
using more that 1 GPU

### ISSUE THREAD

**Issue by alexxrobert** [ZigaMr/ReverseProfanityTool#3]
How can I run in multiGPU? 
In single GPU I set the PYOPENCL_CTX=0 but with 2 GPU, it first asks [0] <pyopencl.Platform 'NVIDIA CUDA
and then lists GPUs and I chose 0,1 but i see only 1 GPU is used (in nvidia-smi)

**Comment by ZigaMr** [comment]
It wasn't built for multiple GPUs, but should be trivial to add in the future if I have time.
