### ISSUE TITLE
kindly help resolve this 

### ISSUE THREAD

**Issue by ahsanmirz** [ZigaMr/ReverseProfanityTool#5]
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/14/e3q8)
 
i have done the same as its describe but not working. on macbook M1

**Comment by ZigaMr** [comment]
Try pulling the latest changes, it didn't create the 'DB' folder before.

**Comment by ahsanmirz** [comment]
Device name: Apple M1
Device type: ALL | GPU
Device memory: 5461.34375 MB
Choose platform:
[0] <pyopencl.Platform 'Apple' at 0x7fff0000>
Choice [0]:0
Set the environment variable PYOPENCL_CTX='0' to avoid being asked again.
Initializing pubKeys...
_read_8byte_pubkey took 1.946484 seconds
Fetching deployers, contract count:  0
Traceback (most recent call last):
  File "/Users/apple123/Downloads/ReverseProfanityTool-main/myenv/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           
           "Still having issues "

**Comment by ZigaMr** [comment]
Try setting the keys in your config.json.

**Comment by ahsanmirz** [comment]
"ethereum": {
    "w3": "https://etherscan.io/myapikey_stats?apikey=******CET6WN**********J66HGCDJHN****",
    "etherscan_key": "******CET6WN**********J66HGCDJHN****",
    "base_url": "https://etherscan.io/myapikey"
   
   
    "am i doing it the right way ?"
    bc i still having errors  e.g
   
   
    Device name: Apple M1
Device type: ALL | GPU
Device memory: 5461.34375 MB
Choose platform:
[0] <pyopencl.Platform 'Apple' at 0x7fff0000>
Choice [0]:a
Set the environment variable PYOPENCL_CTX='a' to avoid being asked again.
Initializing pubKeys...
_read_8byte_pubkey took 1.415774 seconds
Fetching deployers, contract count:  1
Traceback (most recent call last):
  File "/Users/apple123/Downloads/ReverseProfanityTool-main/main.py", line 31, in <module>
    eoas = prof.get_deployers(contracts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple123/Downloads/ReverseProfanityTool-main/src/tools.py", line 459, in get_deployers
    res = self._get_etherscan_deployers(contract_addresses[counter:min(counter + 5, list_len)])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple123/Downloads/ReverseProfanityTool-main/src/tools.py", line 436, in _get_etherscan_deployers
    "contractaddresses": ",".join(contract_addresses), "apikey": self.etherscan_api_key}
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, int found

**Comment by ahsanmirz** [comment]
(myenv) apple123@ ReverseProfanityTool-main % pip3 install pywin32
ERROR: Could not find a version that satisfies the requirement pywin32 (from versions: none)
ERROR: No matching distribution found for pywin32


"what i have found that pywin32 can not get install on mac . do u have other opentions  ?"
